//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NVT.lib.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NVT.lib.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not locate config file - reinstall.
        /// </summary>
        public static string LogConfigurationManager_FileNotFound {
            get {
                return ResourceManager.GetString("LogConfigurationManager_FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to connections found.
        /// </summary>
        public static string MainViewModel_ConnectionStatus_Plural {
            get {
                return ResourceManager.GetString("MainViewModel_ConnectionStatus_Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to connection found.
        /// </summary>
        public static string MainViewModel_ConnectionStatus_Singular {
            get {
                return ResourceManager.GetString("MainViewModel_ConnectionStatus_Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully saved the settings.
        /// </summary>
        public static string MainViewModel_Settings_SavedSuccessfully {
            get {
                return ResourceManager.GetString("MainViewModel_Settings_SavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when saving.
        /// </summary>
        public static string MainViewModel_Settings_SavedUnsuccessfully {
            get {
                return ResourceManager.GetString("MainViewModel_Settings_SavedUnsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NVT is a Network Connection Tool to better inform you as the end-user what connections are on your machine.
        /// </summary>
        public static string MainWindow_About {
            get {
                return ResourceManager.GetString("MainWindow_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source code on GitHub.
        /// </summary>
        public static string MainWindow_About_SourceLink {
            get {
                return ResourceManager.GetString("MainWindow_About_SourceLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Log.
        /// </summary>
        public static string MainWindow_About_ViewLogButton {
            get {
                return ResourceManager.GetString("MainWindow_About_ViewLogButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string MainWindow_AboutHeader {
            get {
                return ResourceManager.GetString("MainWindow_AboutHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (actively querying).
        /// </summary>
        public static string MainWindow_ActivelyQuerying {
            get {
                return ResourceManager.GetString("MainWindow_ActivelyQuerying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Address copied to clipboard.
        /// </summary>
        public static string MainWindow_Copy_IPAddress {
            get {
                return ResourceManager.GetString("MainWindow_Copy_IPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string MainWindow_Grid_Header_Actions {
            get {
                return ResourceManager.GetString("MainWindow_Grid_Header_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string MainWindow_Grid_Header_City {
            get {
                return ResourceManager.GetString("MainWindow_Grid_Header_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string MainWindow_Grid_Header_Country {
            get {
                return ResourceManager.GetString("MainWindow_Grid_Header_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detection.
        /// </summary>
        public static string MainWindow_Grid_Header_Detection {
            get {
                return ResourceManager.GetString("MainWindow_Grid_Header_Detection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Address.
        /// </summary>
        public static string MainWindow_Grid_Header_IPAddress {
            get {
                return ResourceManager.GetString("MainWindow_Grid_Header_IPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISP.
        /// </summary>
        public static string MainWindow_Grid_Header_ISP {
            get {
                return ResourceManager.GetString("MainWindow_Grid_Header_ISP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string MainWindow_Grid_Header_Port {
            get {
                return ResourceManager.GetString("MainWindow_Grid_Header_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process File Name.
        /// </summary>
        public static string MainWindow_Grid_Header_ProcessFileName {
            get {
                return ResourceManager.GetString("MainWindow_Grid_Header_ProcessFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string MainWindow_Grid_Header_Type {
            get {
                return ResourceManager.GetString("MainWindow_Grid_Header_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Connections.
        /// </summary>
        public static string MainWindow_Grid_Tooltip {
            get {
                return ResourceManager.GetString("MainWindow_Grid_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find log file to open.
        /// </summary>
        public static string MainWindow_LogFileNotFound {
            get {
                return ResourceManager.GetString("MainWindow_LogFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No current TCP Connections found.
        /// </summary>
        public static string MainWindow_NoConnectionsFound {
            get {
                return ResourceManager.GetString("MainWindow_NoConnectionsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Lookup.
        /// </summary>
        public static string MainWindow_Settings_EnableLookup {
            get {
                return ResourceManager.GetString("MainWindow_Settings_EnableLookup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable/Disable.
        /// </summary>
        public static string MainWindow_Settings_EnableLookup_ToggleText {
            get {
                return ResourceManager.GetString("MainWindow_Settings_EnableLookup_ToggleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Level.
        /// </summary>
        public static string MainWindow_Settings_LogLevels {
            get {
                return ResourceManager.GetString("MainWindow_Settings_LogLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Lookup Service URL.
        /// </summary>
        public static string MainWindow_Settings_LookupURL {
            get {
                return ResourceManager.GetString("MainWindow_Settings_LookupURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string MainWindow_Settings_SaveButton_Label {
            get {
                return ResourceManager.GetString("MainWindow_Settings_SaveButton_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scannable Connection Types.
        /// </summary>
        public static string MainWindow_Settings_ScannableConnectionTypes {
            get {
                return ResourceManager.GetString("MainWindow_Settings_ScannableConnectionTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string MainWindow_SettingsHeader {
            get {
                return ResourceManager.GetString("MainWindow_SettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred when exporting the connections - please try again.
        /// </summary>
        public static string MainWindowCommand_Export_Message_Error {
            get {
                return ResourceManager.GetString("MainWindowCommand_Export_Message_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No connections found - aborting export.
        /// </summary>
        public static string MainWindowCommand_Export_Message_NoConnections {
            get {
                return ResourceManager.GetString("MainWindowCommand_Export_Message_NoConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connections exported to.
        /// </summary>
        public static string MainWindowCommand_Export_Message_Success {
            get {
                return ResourceManager.GetString("MainWindowCommand_Export_Message_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string MainWindowCommand_Tooltips_About {
            get {
                return ResourceManager.GetString("MainWindowCommand_Tooltips_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export connections to file.
        /// </summary>
        public static string MainWindowCommand_Tooltips_Export {
            get {
                return ResourceManager.GetString("MainWindowCommand_Tooltips_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjust settings.
        /// </summary>
        public static string MainWindowCommand_Tooltips_Settings {
            get {
                return ResourceManager.GetString("MainWindowCommand_Tooltips_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to kill process.
        /// </summary>
        public static string ProcessManager_KillProcess_Failure {
            get {
                return ResourceManager.GetString("ProcessManager_KillProcess_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully killed process.
        /// </summary>
        public static string ProcessManager_KillProcess_Success {
            get {
                return ResourceManager.GetString("ProcessManager_KillProcess_Success", resourceCulture);
            }
        }
    }
}
